spring:
  datasource:
    url: jdbc:h2:mem:event_management
    username: sa
    password: password
    driverClassName: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
logging:
  level:
    root: INFO